### ISSUE TITLE
John Lewis Issue

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#37] opened 2014-02-19 20:55 UTC
Just had the same problem running from the server from home. Could it possibly be storing this location in a file and using it to load from instead of using the dynamic one (from geolocation) or static zoomed out view?

**Comment by allyjweir** [comment] 2014-02-19 20:56
![johnlewisissue](https://f.cloud.github.com/assets/3640069/2211646/3915e298-99a8-11e3-8759-f27e4b13409a.PNG)

**Comment by calxus** [comment] 2014-02-19 21:00
I love the name of this issue, i'll check this out.

**Comment by calxus** [comment] 2014-02-19 21:27
I'm going to leave this on the backburner right now. And hope it just goes away. 

There are literally no logical answers as to why this should be the case, besides geolocation having a bug, whereby it chooses to sometimes say you are in a john lewis department store.

**Comment by calxus** [comment] 2014-02-23 20:59
I was told I was in Edinburgh Waverly Station temporarily yesterday so I assume this issue is just with geolocation freaking out sometimes. I'm going to close it, but if the issue ever becomes a real problem we can reopen it again.

**Closed as completed by calxus** 2014-02-23 20:59 UTC
Labels: bug

**Comment by calxus** [comment] 2014-03-18 01:18
I recently changed to bt infinity, now I am experiencing this john lewis issue when I never have before. I don't know what the problem is, but there has to be some sort of connection.
